# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-05 11:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pm_module', '0002_auto_20170105_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='project_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
