# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-05 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm_module', '0003_auto_20170105_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='actual_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Actual End Date'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='actual_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Actual Start Date'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='client_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Client Name'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
    ]
